resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: ghcr.io/gamebeastgg/valkey-operator
  newTag: v1.1.0-fix1
commonAnnotations:
  defaultExporterImageName: oliver006/redis_exporter
  defaultExporterVersion: v1.67.0-alpine
  defaultRegistry: ""
  operatorImageName: ghcr.io/gamebeastgg/valkey-operator
  operatorVersion: v1.1.0-fix1
  valkeyImageName: valkey/valkey
  valkeyVersionMap: '{}'
